# Generated by Django 4.2 on 2023-04-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_rename_caarga_horario_evento_caarga_horaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='caarga_horaria',
            new_name='caarga_horario',
        ),
    ]
