# Generated by Django 4.2 on 2023-04-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_rename_carga_horaria_evento_caarga_horaria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='caarga_horaria',
            new_name='carga_horaria',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='data_inico',
            new_name='data_inicio',
        ),
    ]
